sudo: required

language: python

services:
  - docker

matrix:
  include:
  - name: "py2"
    env: PY_VER=2.7 CUDA=""
#  - name: "py2, cuda"  ## THE BUILD TIME EXCEED THE TRAVIS LIMIT
#    env: PY_VER=2.7 CUDA="_cuda"
#  - name: "py35"  ## NOT SUPPORTED FOR UBUNTU 18.04
#    env: PY_VER=3.5 CUDA=""
  - name: "py36"
    env: PY_VER=3.6 CUDA=""
  - name: "py37"
    env: PY_VER=3.7 CUDA=""
#  - name: "py3, cuda"  ## THE BUILD TIME EXCEED THE TRAVIS LIMIT
#    env: PY_VER=3.6 CUDA="_cuda"
  - name: "py38"
    env: PY_VER=3.8 CUDA=""

install:
  - docker build -t ubuntu-py$PY_VER$CUDA -f cpu/Dockerfile$CUDA --build-arg PYTHON_VERSION=$PY_VER .

script:
  - docker images
  - docker run -i -t ubuntu-py$PY_VER$CUDA pip --version
  - docker run -i -t ubuntu-py$PY_VER$CUDA python -c "import cv2 ; print(cv2.__version__)"

